jenkins:
    systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
    numExecutors: 0
    mode: NORMAL
    securityRealm:
      local:
        allowsSignup: false
        users:
          - id: admin
            password: azerty
          - id: newuser
            password: pomme
    